export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_TODAY_ATTENDANCE = "SET_TODAY_ATTENDANCE"
export const SET_ATTENDANCE_HISTORY = "SET_ATTENDANCE_HISTORY"
export const SET_LOCATION = "SET_ATTENDANCE_HISTORY"
export const SET_TIME_SERVER = "SET_TIME_SERVER"
export const SET_LOGIN_TOKEN = "SET_LOGIN_TOKEN"

